# Generated by Django 5.0 on 2023-12-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeTitles',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('overview', models.TextField()),
                ('broadcast', models.DateField()),
                ('img', models.ImageField(upload_to='media')),
                ('Officialsite', models.URLField(null=True)),
                ('pv', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag', models.TextField(null=True)),
                ('graph', models.TextField(null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_api.animetitles')),
            ],
        ),
    ]
