# Generated by Django 5.0 on 2023-12-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
