# Generated by Django 5.0 on 2024-01-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0003_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animetitles',
            old_name='Officialsite',
            new_name='officialsite',
        ),
    ]
