# Generated by Django 5.0 on 2024-07-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0004_rename_officialsite_animetitles_officialsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animetitles',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
