# Generated by Django 5.0 on 2024-03-15 09:35

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime_api', '0004_rename_officialsite_animetitles_officialsite'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(db_comment='システムユーザID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_comment='メールアドレス', max_length=255, unique=True)),
                ('username', models.CharField(db_comment='ユーザ名', max_length=34)),
                ('password', models.CharField(db_comment='パスワード', max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_comment='有効の有無', default=True)),
                ('icon', models.ImageField(blank=True, db_comment='プロフィール画像', null=True, upload_to='icon')),
                ('user_identifier', models.CharField(db_comment='ユーザ識別子', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='作成日')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('unique_username', models.CharField(db_index=True, max_length=37, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'unique_together': {('username', 'user_identifier')},
            },
        ),
        migrations.CreateModel(
            name='TwoFactorEmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 20, 35, 53, 169248))),
                ('trycount', models.IntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationTokenModel',
            fields=[
                ('token', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expiry', models.DateTimeField(auto_now_add=True)),
                ('purpose_reset_password', models.BooleanField(null=True)),
                ('purpose_regist_user', models.BooleanField(null=True)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoritesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False)),
                ('anime_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime_api.animetitles')),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('anime_title', 'uuid')},
            },
        ),
        migrations.CreateModel(
            name='ReviewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=32)),
                ('body', models.TextField(max_length=1024)),
                ('star', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime_api.animetitles')),
                ('author', models.ForeignKey(default='test12#197', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='unique_username')),
            ],
            options={
                'unique_together': {('anime_title', 'author')},
            },
        ),
    ]
