# Generated by Django 5.0 on 2024-04-11 05:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_reviewsmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 16, 21, 5, 539764)),
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, db_comment='プロフィール画像', null=True, upload_to='icon')),
                ('status_message', models.CharField(db_comment='ステータスメッセージ', max_length=128, null=True)),
                ('background', models.ImageField(blank=True, db_comment='背景', null=True, upload_to='icon')),
                ('uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
