# Generated by Django 5.0 on 2024-04-25 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_twofactoremailmodel_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 4, 2, 25, 963062)),
        ),
    ]
