# Generated by Django 5.0 on 2024-04-28 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_twofactoremailmodel_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 20, 2, 54, 53107)),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='background',
            field=models.CharField(blank=True, db_comment='背景', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='icon',
            field=models.CharField(blank=True, db_comment='プロフィール画像', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='icon',
            field=models.CharField(blank=True, db_comment='プロフィール画像', max_length=100, null=True),
        ),
    ]
