# Generated by Django 5.0 on 2024-05-21 13:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_twofactoremailmodel_expiration_and_more'),
        ('anime_api', '0004_rename_officialsite_animetitles_officialsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 0, 13, 55, 748127)),
        ),
        migrations.CreateModel(
            name='UserSelectAnimeTrackingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='作成日')),
                ('select_anime', models.ForeignKey(db_comment='選択されたアニメ', on_delete=django.db.models.deletion.PROTECT, to='anime_api.animetitles')),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
