# Generated by Django 5.0 on 2024-07-04 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_twofactoremailmodel_expiration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='icon',
        ),
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 14, 7, 43, 363630)),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='background',
            field=models.ImageField(db_comment='背景', null=True, upload_to='user_profile/background/'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='icon',
            field=models.ImageField(db_comment='プロフィール画像', null=True, upload_to='user_profile/icon/'),
        ),
    ]
